In [276]:
import numpy as np
import pandas as pd

In [277]:
df=pd.read_csv('startup_funding.csv')
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [278]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [279]:
df.drop(columns=['Remarks'],inplace=True)

In [280]:
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [281]:
df.set_index('Sr No',inplace=True)

In [282]:
df.head()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [283]:
df.rename(columns={
    'Date dd/mm/yyyy':'date',
    'Startup Name':'startup',
    'Industry Vertical':'vertical',
    'SubVertical':'subvertical',
    'City  Location':'city',
    'Investors Name':'investors',
    'InvestmentnType':'round',
    'Amount in USD':'amount'    
    
},inplace=True)

In [284]:
df.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [285]:
df['amount']=df['amount'].fillna('0')

In [286]:
df['amount'] = df['amount'].str.replace(',','')
df['amount'] = df['amount'].str.replace('undisclosed','0')
df['amount'] = df['amount'].str.replace('unknown','0')
df['amount'] = df['amount'].str.replace('Undisclosed','0')

In [287]:
df = df[df['amount'].str.isdigit()]

In [288]:
df['amount']=df['amount'].astype('float')

In [289]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3029 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3029 non-null   object
 1   startup      3029 non-null   object
 2   vertical     2858 non-null   object
 3   subvertical  2104 non-null   object
 4   city         2849 non-null   object
 5   investors    3005 non-null   object
 6   round        3027 non-null   object
 7   amount       3029 non-null   float64
dtypes: float64(1), object(7)
memory usage: 213.0+ KB

In [290]:



def to_inr(dollar):
    inr = dollar * 82.5
    return inr/10000000

In [291]:
df['amount']=df['amount'].apply(to_inr)

In [292]:
df.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1650.000000
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,66.399250
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,151.460595
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,24.750000
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,14.850000

In [293]:
df['date'] = df['date'].str.replace('05/072018','05/07/2018')

In [ ]:
df['date'] = pd.to_datetime(df['date'],errors='coerce')
df['date'] = pd.to_datetime(df['date'],errors='coerce')

In [297]:
df.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,2020-09-01,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1650.000000
2,NaT,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,66.399250
3,2020-09-01,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,151.460595
4,2020-02-01,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,24.750000
5,2020-02-01,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,14.850000

In [ ]:
df = df.dropna(subset=['date','startup','vertical','city','investors','round','amount'])
df = df.dropna(subset=['date','startup','vertical','city','investors','round','amount'])

In [299]:
df.to_csv('cleaned_startup_funding.csv',index=False)

In [ ]:
sorted(set(df['investors'].str.split(',').sum()))
sorted(set(df['investors'].str.split(',').sum()))

['',
 ' & Others',
 ' 500 Start-Ups',
 ' 500 Startups',
 ' 91springboard',
 ' ABCOM Investments',
 ' AECAL',
 ' AET Fund',
 ' ASP Consulting',
 ' AVN Business Solutions',
 ' Aarin Capital',
 ' Aarin Capital & Others',
 ' Aaruha Technology Fund',
 ' Abaran Deep',
 ' Abhai S. Rao',
 ' Abhay Singhal',
 ' Abhinav Patodia',
 ' Abhishek Goyal',
 ' Abhishek Gupta',
 ' Abhishekh Goyal',
 ' Abstract Ventures',
 ' Accel India',
 ' Accel Partners',
 ' Accel Partners & Others',
 ' Accel Partners and G Raghunandan',
 ' Accel Partners and IDG Ventures',
 ' Accel Partners and Saama Capital',
 ' Accion',
 ' Adam D\\\\xe2\\\\x80\\\\x99Angelo',
 ' Aditya Agarwal',
 ' Aditya Aggarwal',
 ' Aditya Malik & Others',
 ' Aditya Vazirani',
 ' AdvantEdge Partners',
 ' Adveq Management',
 ' Aijaz Saleem',
 ' Ajay Bhatia',
 ' Ajeet Khurana & others',
 ' Akatsuki and Incubate Fund from Japan and Better Capital AngelList syndicate.',
 ' Alfa Capital',
 ' Alok Divatia',
 ' Alok Mittal',
 ' Alok Sharma',
 ' Aloke Bajpai',
 ' Alphabet\\\\xe2\\\\x80\\\\x99s growth investment arm Capital G and Axis Bank',
 ' Altimeter Capital',
 ' Amereus Group',
 ' American Express',
 ' American Express Ventures',
 ' Amit Banati',
 ' Amit Gupta',
 ' Amit Jindal',
 ' Amit Khanna',
 ' Amit Manocha',
 ' Amit Nagar',
 ' Amit Nanavati',
 ' Amit Ranjan',
 ' Amit Rathore',
 ' Amit Sinha',
 ' Amrendra Reddy and Manish Satnaliwala.',
 ' Amrish Kumar',
 ' Amrish Rau',
 ' Anand Chandrasekaran',
 ' Anand Ladsariya',
 ' Anand Mahindra',
 ' Anand Sankeshwar',
 ' Anand Singh',
 ' Ananda Kallugadde',
 ' Andre Hoffman',
 ' Aneesh Reddy',
 ' Anil Gelra',
 ' Anil Jaggia',
 ' Anindya Ghose',
 ' Anirudh Damani',
 ' Anisha Mittal',
 ' Anita Gupta',
 ' Anjali Bansal',
 ' Ankit Aditya',
 ' Ankit Bhati',
 ' Ankit Sharma and others',
 ' Ankur Singla',
 ' Ankur Warikoo',
 ' Ankush Gupta',
 ' Ankush Nijhawan',
 ' Ankush Saigal',
 ' Anoop Hingorani',
 ' Anshul Jindal',
 ' Anthill Ventures',
 ' Anubhav Verma',
 ' Anuj Gupta',
 ' Anuj Puri',
 ' Anuj Sanghi',
 ' Anupam Mittal',
 ' Anupam Tyagi',
 ' Apoletto',
 ' Apoorv Ranjan Sharma',
 ' Apoorva Patni',
 ' Appliyifi',
 ' Aprameya Radhakrishna',
 ' Apurva Chamaria',
 ' Apurva Salarpuria',
 ' Aqeel Ahmed',
 ' Arihant Patni',
 ' Arihant Patni of Patni Family Office',
 ' Arjun Mehta',
 ' Arjun Sharmaa',
 ' Arkas Industries',
 ' Artha India Ventures',
 ' Artiman Ventures',
 ' Arts Alliance',
 ' Arun Garg',
 ' Arun Khanna',
 ' Arun Tadanki',
 ' Arun Venkatachalam',
 ' Arvind Uppal',
 ' Ascent Capital',
 ' Aseem Sood',
 ' Ashim Mehra',
 ' Ashish Dhawan',
 ' Ashish Goenka',
 ' Ashish Gupta',
 ' Ashneer Grover',
 ' Ashvin Chadha',
 ' Aspada',
 ' Aspada Ventures',
 ' Atul Nishar',
 ' Atul Phadnis',
 ' Augment Ventures',
 ' Avtar Monga',
 ' Axan Partners',
 ' Axan Venture',
 ' Axilor Ventures',
 ' Axis Capital',
 ' Axon Partners',
 ' Azmul Haque',
 ' B Capital',
 ' BEENEXT',
 ' BEENEXT Ventures',
 ' Balamurugan Mani',
 ' Bamboo Capital Partners',
 ' Barkawi Holdings GmbH',
 ' Batlivala & Karani Securities',
 ' Bedrock Ventures',
 ' BeeNext',
 ' Beehive Capital Advisor',
 ' Beenext',
 ' Beenext Ventures',
 ' Beenextan investment fund',
 ' Beenos',
 ' Behram Vakil and Jerxis Vandrevala',
 ' Bennett Coleman & Co. Ltd',
 ' Berggruen Holdings',
 ' Bertelsmann India',
 ' Bertelsmann India Investments',
 ' Bessemer Venture Partners',
 ' Bharat Gupta',
 ' Bharat Kedia',
 ' Bhavish Aggarwal',
 ' Big Data Investments B.V',
 ' Binny Bansal',
 ' BizReach',
 ' Blume Ventures',
 ' Blume Ventures & IvyCap Ventures',
 ' Blume Ventures & Others',
 ' Blume Ventures.',
 ' Brand Capital',
 ' Burda Principal Investments',
 ' C31 Ventures',
 ' CCavenue',
 ' CDC Group',
 ' CSC Upshot & Angel investors',
 ' Calcutta Angels',
 ' Capricorn Investment Group',
 ' Capricorn Investment and IFC',
 ' Caspian and Hivos-Triodos Fund',
 ' Catamaran Ventures',
 ' Chandru Badrinarayanan',
 ' Cisco Investments',
 ' Coleman and Company Ltd',
 ' Contrarian Capital',
 ' Contrarian Capital India Partners',
 ' Corvus Ventures',
 ' Currae Healthtech Fund',
 ' Cyber Carrier VC',
 ' CyberAgent Ventures',
 ' DSG Consumer Partners and Venture Nursery',
 ' DST Global',
 ' DST Partners and RPS Ventures',
 ' Dalip Pathak',
 ' Darius Pandole',
 ' Darrin Capital',
 ' Darshan Upadhyay',
 ' Das Capital and IT Farm',
 ' Daud Ali',
 ' Daud Ali and others',
 ' Deep Kalra',
 ' Deepak Ghaisas',
 ' Deepak Jain',
 ' Deepak Sharma',
 ' Deepinder Goyal',
 ' Deobrat Singh',
 ' Deshe Holdings',
 ' Deshpande Foundation',
 ' Dewan Housing Finance Corp',
 ' Dheerag Jain',
 ' Dheeraj Jain',
 ' Digital Currency Group',
 ' Digital Garage',
 ' Digital Garage Inc',
 ' Dileep Nath',
 ' Dinesh Agarwal',
 ' Dinesh Kundu & others',
 ' Dinesh Mittal',
 ' Doreswamy Nandkishore',
 ' Dr Paresh Doshi',
 ' Dr. Aniruddha Malpani',
 ' Dr. Apoorv Ranjan Sharma',
 ' Dr. Prasad Kaipa',
 ' Dr. Ranjan Pai',
 ' Dr. Ritesh Malik',
 ' Draper Associates',
 ' Dreamweaver Investments',
 ' E.ON',
 ' EDBI',
 ' Edelweiss Private Equity',
 ' Eight Innovate',
 ' Eight Roads Ventures',
 ' Eight Roads Ventures India',
 ' Elevar Equity',
 ' Elevar Equity and Accel Partners',
 ' Elevate Sports',
 ' Emergent Ventures',
 ' Emergent Ventures India',
 ' Empire Angels',
 ' Endiya Partners',
 ' Entrepreneurs India',
 ' Evan Lim',
 ' Excelsior Investments',
 ' Exfinity Ventures',
 ' Existing investors',
 ' F-Prime Capital Partners',
 ' Faering Capital',
 ' Farhan Naqvi',
 ' Fauzan Rahim',
 ' Fenqile',
 ' Fidelity Biosciences',
 ' Fidelity Growth Partners',
 ' Fidelity Growth Partners India',
 ' Fireside Ventures',
 ' Flipkart',
 ' Florintree Advisors',
 ' Fosun RZ Capital',
 ' Foxconn',
 ' Fred Khosravi',
 ' Frontline Strategy',
 ' G Ravishankar',
 ' GHV Accelerator',
 ' GREE Ventures',
 ' GSF and Other angel investors',
 ' GVFL',
 ' Gabriel Investments',
 ' Gagan Hasteer ',
 ' Ganpat Singhvi',
 ' Gaurav Bhatnagar',
 ' Gaurav Dalmia',
 ' Gaurav Gupta',
 ' Gaurav Lochan',
 ' Gaurav Sharma',
 ' Gaurav Suri and Ankit Kesarwani',
 ' Gaurav Vats',
 ' Gautam Chhaochharia',
 ' Gautam Gandhi',
 ' Girish Mathrubootham',
 ' Girnar Software',
 ' Globeinvestor',
 ' Goa',
 ' Gokul Rajaram',
 ' Google Capital',
 ' Govind Rajan & Others',
 ' Grace Capital Ventures',
 ' Green Shots Capital',
 ' Greenoaks Capital',
 ' Grey Orange Robotics',
 ' Greycroft Partners',
 ' GrowX Ventures',
 ' Gyanendra Singh',
 ' HDFC Asset Management',
 ' Haresh Chawla',
 ' Harmony Partners',
 ' Harsh Kundra',
 ' Harvard Angels',
 ' Healthsquad',
 ' Helion Advisors',
 ' Helion Venture',
 ' Helion Venture Partners',
 ' Helion Ventures',
 ' Herb Madan',
 ' Hermes Group',
 ' Hero Enterprise',
 ' Hetal Sonpal',
 ' Hillhouse Capital',
 ' Himanshu Aggrawal',
 ' Hinduja Group',
 ' Hinduja Leyland Finance and IntelleGrow',
 ' Hiro Mashita',
 ' Horseferry',
 ' Hrishi Oberoi',
 ' Hrishikesh Parandekar',
 ' Huang Wei',
 ' IDFC-Parampara Fund',
 ' IDG Ventures',
 ' IDG Ventures & Advantedge fund',
 ' IDG Ventures & Indian Angel Network',
 ' IDG Ventures India',
 ' IIFL Wealth',
 ' ILearnFinance Academy Pvt. Ltd.',
 ' IMJ Investment Partners',
 ' Ideation Initiative Pvt. Ltd',
 ' InMobi',
 ' Inc',
 ' India Alternatives',
 ' India Internet Fund',
 ' India Quotient',
 ' Indian Angel Network',
 ' Indian Angel Network (IAN)',
 ' Individual Investors',
 ' Indus Age Partners',
 ' Infuse Ventures',
 ' Innogy',
 ' Innov8',
 ' Innov8 founder Ritesh Malik',
 ' Intel Capital',
 ' Intellecap Impact Investment Network',
 ' International Finance Corporation (IFC)',
 ' Internet Group',
 ' Inventus Capital',
 ' Inventus Capital Partners',
 ' Investment AB Kinnevik',
 ' Investopad',
 ' IvyCap Ventures',
 ' JAFCO Asia',
 ' JLL',
 ' JM Financials and MEMG',
 ' Jagdish & Sandeep Mehta Family Office',
 ' Jagdish Kumar',
 ' Jaikumar Nair',
 ' Jarett Posner',
 ' Jason Hirschhorn',
 ' Jay Srinivasan',
 ' Jayant Davar',
 ' Jayesh Parekh',
 ' Jayesh Shah',
 ' Jeroen Mensen',
 ' Jim Schimdktke',
 ' Jitendra Gupta',
 ' Jonathan Boutelle',
 ' Josh Talks founders Supriya Paul and Shobha Banga',
 ' Jungle Venture Partners',
 ' Jungle Ventures',
 ' Jungle Ventures & Bessemer Venture Partners',
 ' K Ganesh',
 ' Kae Capital',
 ' Kae Capital & Others',
 ' Kalaari Capital',
 ' Kalaari Capital and Private equity firm Multiples Alternate Asset Management',
 ' Kanchan Ghoshal',
 ' Kapil Hetamsaria',
 ' Karan Chellani',
 ' Keith Rodricks',
 ' Keshav Sanghi',
 ' Khazanah Nasional Berhad',
 ' Khosla Impact',
 ' Khosla Ventures',
 ' Kima Ventures',
 ' Kiran Deshpande',
 ' Kris Gopalakrishnan',
 ' Krishna Jhunjhunwaala',
 ' Krishna Mehra',
 ' Kshitij Jain',
 ' Kumar Shwetabh',
 ' Kumar Vembu',
 ' Kunal Bahl',
 ' Kunal Khattar',
 ' Kunal Shah',
 ' Kunal Shah & Sandeep Tandon',
 ' L.D Sharma',
 ' LGT Impact',
 ' LN Buddharaju',
 ' Lalit Mangal',
 ' Leo Wang Sangeeth Ram',
 ' Leon Seynave',
 ' LetsVenture',
 ' Liberty Media',
 ' LightStreet',
 ' Lightbox',
 ' Lightbridge Partners & Kairos',
 ' Lightspeed India',
 ' Lightspeed Venture Partners',
 ' Lightspeed Ventures',
 ' Likemind Ventures',
 ' Lomesh Agarwal',
 ' M&S Partners',
 ' MAPE Advisory Group',
 ' MJ Aravind',
 ' Madhusudan E',
 ' Maiden Lane Ventures',
 ' MakeMyTrip',
 ' Mandhian family & Others',
 ' Manickam Mahalingam',
 ' Manish Dhingra',
 ' Manish Prasad',
 ' Manvinder Singh Banga',
 ' Mape Advisory Group',
 ' Mariwala family',
 ' Mato Peric',
 ' Matrix Partners',
 ' Mayank Singhal',
 ' Mayfield',
 ' Mayfield & Others',
 ' Mayfield Capital',
 ' Mayur Abhaya',
 ' MediaTek',
 ' Mekin Maheshwari',
 ' MeraEvents.',
 ' Michael & Susan Dell Foundation',
 ' Michael Carlos',
 ' Michael Marks',
 ' Mike Galgon',
 ' Milind Sarwate',
 ' Mistletoe',
 ' Mohandas Pai',
 ' Mohit Agarwal',
 ' Mohit Gupta',
 ' Mohit Satyan',
 ' Mohit Satyanand',
 ' Mohit Satyanand & others',
 ' Moksh Sports Ventures',
 ' Mousse Partners',
 ' Mr. Praveen Someshwar',
 ' Mridul Upreti',
 ' Mukul Singhal',
 ' Multiples Alternate Asset Management',
 ' Mumbai Angel',
 ' Mumbai Angels',
 ' Mumbai Angels Network',
 ' Mustafa Patni',
 ' N Squared Management LLC',
 ' NEA Ventures',
 ' NGP',
 ' Nagendra Chaudhary',
 ' Namrata Kaul',
 ' Nandan Nilekani',
 ' Nandan Nilekani\\\\xe2\\\\x80\\\\x99s NRJN Trust',
 ' Nandkumar Rane',
 ' Narayan Ramachandran',
 ' Narayan Seshadri',
 ' Narendra Karnavat',
 ' Nazara Technologies',
 ' Neeraj Arora',
 ' Neeraj Jawalkar',
 ' Ness Wadia',
 ' Network 18',
 ' Nexus India Capital Advisors',
 ' Nexus Venture Partners',
 ' Nick Haulkoury',
 ' Nicolas Braithwaite',
 ' Nikhil Bagri',
 ' Nikhil Golcha',
 ' Nikhil Vora',
 ' Nikunj Jain',
 ' Nikunj Jhaveri',
 ' Nilender Chauhan',
 ' Nipun Dureja',
 ' Niraj Singh',
 ' Nirav Choksi & Others',
 ' Nirmal Singh',
 ' Nirvana Digital India Fund',
 ' Nirvana Digital Investment Holding Co Ltd',
 ' Nishant Rao',
 ' Nitin Agarwal',
 ' North Base Media',
 ' Norwest Venture Partners',
 ' Nyca Partners and Thomvest Ventures',
 ' Omidyar Network',
 ' Omidyar Network and Kaizen Private Equity also participated in the round',
 ' Orios Venture Partners',
 ' Others',
 ' Others from LetsVenture',
 ' P.V SIndhu',
 ' PV Srinivasan',
 ' Pablo van den Bosch & Others',
 ' Pallav Nadhani',
 ' Pankaj Gupta',
 ' Paragon Partners',
 ' Parekh Marine Transport',
 ' Parmeshwar Sharma',
 ' Partech Ventures',
 ' Paul Bucche',
 ' Pavan Bakeri',
 ' Pavan Ongole',
 ' Paytm',
 ' Perceptive Advisors',
 ' Peter Kabel & others',
 ' Phanindra Sama',
 ' Pidilite Industries director Ajay Parekh',
 ' Piyush Shah',
 ' Powerhouse Ventures',
 ' Pramod Bhasin',
 ' Pramod Jain',
 ' Pranav Dedhia',
 ' Pranav Pai',
 ' Prashant Gupta and Others',
 ' Prashant Malik and others',
 ' Prashant Tandon',
 ' Prathithi Investment Trust',
 ' Praveen Saini',
 ' Praveen Sinha',
 ' Praveer Kumar',
 ' Pravega Ventures',
 ' Pravin Gandhi',
 ' Prime Venture Partners',
 ' Prime Venture Partners and Others',
 ' Priti Padhy',
 ' Pullela Gopichand',
 ' Puneet Dalmia & Others',
 ' Punit Goyal',
 ' Purvi Capital',
 ' Qasar Younis',
 ' Qualcomm Ventures',
 ' Qualgro',
 ' Quarizon',
 ' Quilvest',
 ' Quintillion Media',
 ' R Balachandar',
 ' R Ramaraj',
 ' R. Natarajan',
 ' RB investments & Others',
 ' RNT Capital',
 ' RWE',
 ' Raghunandan G',
 ' Rahul Garg',
 ' Rahul Gautam & Others',
 ' Rahul Kayan',
 ' Rahul Khanna',
 ' Rahul Mehta',
 ' Rajan Anandan',
 ' Rajat Gupta & Others',
 ' Rajesh Arora',
 ' Rajesh K Murthy',
 ' Rajesh Magow',
 ' Rajesh Mahajan',
 ' Rajesh Ranavat',
 ' Rajesh Sawhney',
 ' Rajiv Mehta',
 ' Rajiv Nayan',
 ' Rajiv Solanki',
 ' Rajul Garg',
 ' Rajul Garg & Other undisclosed investors',
 ' Rakesh Desai',
 ' Rakesh Malhotra',
 ' Ram Kumar Kakani',
 ' Ramakant Sharma',
 ' Ratan Tata',
 ' Ravi Garkipati',
 ' Ravi Gururaj',
 ' Ravi Jaipuria & others',
 ' Ravi Nigam & Others',
 ' Ravikanth Reddy',
 ' Real Time Ventures',
 ' Redcliffe Capital',
 ' Reema Kagati',
 ' Renuka Ramanath',
 ' Rhea Vazirani',
 ' Richard S. Braddock',
 ' Riddhesh Gandhi & Others',
 ' RippleWave',
 ' Ritesh Malik',
 ' Ritesh Vohra',
 ' Ritu Kapur',
 ' Rocket Internet',
 ' Rocketship',
 ' Rohan Desai and Paras Patel',
 ' Rohan Malhotra',
 ' Rohit Bansal',
 ' Rohit Jain',
 ' Rohit MA',
 ' Romulus Capital and Kalaari Capital',
 ' Roy Kwan',
 ' Ruchi Narain',
 ' Ruchi Sanghvi & others',
 ' Russian venture capital fund Ru-Net',
 ' SAIF Partners',
 ' SAIF Partners and Kalaari capital',
 ' SAIF Partners and LGT Impact Ventures',
 ' SCM Holdings',
 ' SD Ventures',
 ' SEGNEL Ventures',
 ' SVP Fly Dubai & Others',
 ' Saama Capital',
 ' Saama Capital.',
 ' Sachin Bhatia',
 ' Sadashiva NT',
 ' Saha fund Partners',
 ' Sahil Barua',
 ' Sailender Solanki',
 ' Saket Kumar',
 ' Salesforce Ventures',
 ' Salil Donde',
 ' Samih Toukan and Hussam Khoury',
 ' Samsung and China-based CITIC Capital and others',
 ' Sandeep Acharya & others',
 ' Sandeep Gupta',
 ' Sandeep Pangal',
 ' Sandeep Singh',
 ' Sandeep Tandon',
 ' Sands Capital and International Finance Corporation',
 ' Sanjay Anandaram',
 ' Sanjay Mehta',
 ' Sanjay Mehta & Others',
 ' Sanjay Notani & Others',
 ' Sanjay Sathe',
 ' Sanjay Shenoy',
 ' Sanjeev Kakkar',
 ' Sanjeev Singhal',
 ' Sarvesh Shahra & Others',
 ' Sarvesh Sharma',
 ' Satish Kaul',
 ' Satish Khanna and Taparia family office.',
 ' Sattva Capital',
 ' Satya Muthyala',
 ' Satyajit Heeralal',
 ' Saurab Paruthi',
 ' Saurabh Arora',
 ' Saurabh Srivastava',
 ' SeedPlus',
 ' Seedfund',
 ' Sequoia Capital',
 ' Sequoia Capital Global Equities',
 ' Sequoia Capital India',
 ' Sequoia India',
 ' Shailesh Mehta',
 ' Shailesh Rao',
 ' Shailesh Singh',
 ' Shailesh Viswanathan',
 ' Shamik Sharma',
 ' Sharad Sharma',
 ' Sharad Sharma & 14 others',
 ' Shardul Amarchand Mangaldas',
 ' Shinji Kimura',
 ' Shireesh Palle',
 ' Shomil Pant',
 ' Shripad Nadkarni',
 ' Shubham Gupta',
 ' Shunwei Capital',
 ' Siddharth Banerjee',
 ' Siddharth Kothari',
 ' Siddharth Pai',
 ' Siddharth Parekh',
 ' Sidharth Pansari',
 ' Simile Ventures',
 ' SingTel\\\\xe2\\\\x80\\\\x99s Innov8',
 ' Singapore',
 ' Singapore Angel Network',
 ' Singapore Angel Network & Aseem Vadehra',
 ' Singapore Angel Network.',
 ' Singularity Holdings',
 ' Singularity Ventures and Ravi Dhariwal',
 ' Sirion Labs',
 ' Sistema JSFC and Tanncam Investment',
 ' Sixth Sense',
 ' Sixth Sense Ventures',
 ' Smile Group',
 ' Social Alpha and other unnamed angel investors',
 ' Social+Capital',
 ' Sofina',
 ' Softbank',
 ' Softbank Group',
 ' Sohail Hashemi',
 ' Soham Vencaps',
 ' Sol Primero',
 ' Sonu Bhasin',
 ' Soumitra Sharma',
 ' Sourav Ganguly',
 ' Space Matrix',
 ' Sparknext',
 ' Sprout Capital',
 ' Sprout Venture Partners and others',
 ' Sreepathy Viswanathan',
 ' Stanford Angels',
 ' Steadview Capital',
 ' Stellaris Venture Partners',
 ' Steven Lurie',
 ' Subramanian Ramadorai',
 ' Subramanya SV',
 ' Sudhir Anandarao',
 ' Sujeet Kumar',
 ' Sumit Dayal and others',
 ' Sumit Jain',
 ' Sundar Chanrai',
 ' Sunil Goyal Ashish Gupta',
 ' Sunil Kalra',
 ' Sunil Koul',
 ' Suraj Saharan',
 ' Suresh Shankar',
 ' Surojit Chatterjee',
 ' Susa Ventures',
 ' Sushill Jiwarajka',
 ' Susquehanna International Group.\\\\xc2\\\\xa0 Wavemaker Partners',
 ' Suvo Sarkar',
 ' Sven Hensen',
 ' Swapan Rajdev',
 ' Syngenta AG',
 ' T.V. Mohandas Pai',
 ' TCI Ventures',
 ' TM Service Technology Holdings GmbH',
 ' TNN Capital and others',
 ' TPG Growth',
 ' TR Capital',
 ' TV Mohandas Pai',
 ' Tandem Capital',
 ' Tara India Fund IV and others',
 ' Taranjit Jaswal',
 ' Tarun Adlakha',
 ' Tarun Joshi',
 ' Tarun Khandelwal',
 ' Tashwinder Singh',
 ' Tata Group\\\\xe2\\\\x80\\\\x99s watch and jewellery retailing firm',
 ' The HR Fund',
 ' The Syndicate Fund',
 ' ThirtyThree Investments',
 ' Thomas Assessments and others',
 ' Tiger Global',
 ' Tiger Global And Others',
 ' Tiger Global Management',
 ' Times Internet',
 ' Times Internet Ltd',
 ' Times Internet Ltd & One more Fund',
 ' Toos N Daruvala',
 ' Tracxn Labs',
 ' TracxnLabs',
 ' TransGlobal FZC',
 ' Transmedia Capital',
 ' Trifecta Capital',
 ' Tuscan Ventures',
 ' Tushar Mittal',
 ' Udaan Angels',
 ' Uday Kotak',
 ' Unicorn India Ventures',
 ' Uniqorn Ventures and other',
 ' Unitus Seed Fund',
 ' V Balakrishnan',
 ' V. Balakrishnan',
 ' VC firms India Quotient and Kae Capital',
 ' Vaibhav Jain',
 ' Vaibhav Vohra',
 ' Valiant Capital',
 ' Venk Krishnan',
 ' Venkat Tadanki',
 ' Venkat Vardhan',
 ' Venky Krishnakumar',
 ' Venture Highway',
 ' Venture Works',
 ' VentureEast',
 ' Ventureast',
 ' Venturesity',
 ' Vertex Ventures',
 ' Vikas Kapoor',
 ' Vikas Ranjan',
 ' Vikas Saxena',
 ' Vikram Chachra',
 ' Vikram Kotak',
 ' Vikram Lakhotia',
 ' Vikram Sud',
 ' Vikrant Varshney',
 ' Villgro',
 ' Vinay Mittal',
 ' Vindi Banga',
 ' Vineet Varma',
 ' Vinners',
 ' Vinod Jain & Others',
 ' Vinod Singhal',
 ' Vipul Parekh',
 ' Vishal Gondal',
 ' Vishal Khare',
 ' Vispi Daver',
 ' Vissal Mathew',
 ' Vistaar Investment Advisors Pvt. Ltd.',
 ' Viswanath Ramachandran',
 ' Vivek Bhargava',
 ' Vivek Joshi',
 ' Vy Capital',
 ' Waheed Alli',
 ' WaterBridge Ventures',
 ' Waterbridge Ventures and ThinKuvate',
 ' Wellington',
 ' William Campbell',
 ' Y Combinator',
 ' Y Combinator and Venture Highway',
 ' YCombinator',
 ' Yash Dongre',
 ' Yogesh Andlay',
 ' Yogesh Bansal',
 ' Yogesh Misra',
 ' YouWeCan Ventures',
 ' YourNest Angel Fund',
 ' Yuri Milner',
 ' Zaffiro Ventures',
 ' Zaheer Memon',
 ' Zain Raj',
 ' Zeeshan Hayat',
 ' Zeroth and Artesian Venture Partners',
 ' Zia Mody',
 ' Zishaan Hayath',
 ' Zishaan Hayath and Others',
 ' Zodius Technology Opportunities Fund',
 ' Zop Smart',
 ' Zoya Akhtar',
 ' \\\\xc3\\\\x98rstead',
 ' a Dutch government fund',
 ' ah! Ventures',
 ' ajesh K Murthy',
 ' and Ajai Chowdhry',
 ' and Amit Bhatiani',
 ' and Endiya Partners.\\\\n\\\\n',
 ' and Jamshed Jeejeebhoy',
 ' and Nandan Nilekani',
 ' and Ramakant Sharma',
 ' and Sanjeev Agrawal',
 ' and Sofina',
 ' and Tenaska',
 ' and former Hero Corporate president Rohit Chanana',
 ' chief operating office at IDFC Bank',
 ' director at Byramjee Jeejeebhoy Pvt. Ltd were among the angels',
 ' founder and chairman of career information portal Careers360',
 ' growX ventures',
 ' iSON',
 ' ru-Net',
 ' the UK\\\\xe2\\\\x80\\\\x99s Development Finance Institution and P Surendra Pai',
 ' undisclosed investors',
 '1Crowd',
 '1Crowd (through crowd funding)',
 '1Crowd (through crowdfunding)',
 '3 undisclosed HNIs',
 '3One4 Capital',
 '3one4 Capital',
 '500 Startups',
 '50K Ventures',
 'A M Sikander',
 'A91 Partners',
 'ADAG Reliance Private Equity',
 'AJ Ventures and Jain International Trade Organisation (JITO)',
 'AVG Group',
 'Aakrit Vaish',
 'Aamir Khan',
 'Aarin Capital Partners',
 'Aavishkaar',
 'Aavishkaar Venture Management',
 'Aavya Ventures',
 'Accel Partners',
 'Acumen Fund',
 'Aegon NV',
 'Aequs Group',
 'Agnus Capital',
 'Ajai Chowdhry',
 'Ajay Relan',
 'Ajay Relan and Vinay Mittal',
 'Ajeet Khurana & Others',
 'Ajeet Khurana Jinesh Shah',
 'Ajit Surana',
 'Ajith Sukumaran',
 'Al Dhaheri family',
 'Alex Chua',
 'Alibaba',
 'Alibaba Pictures',
 'Alok Mittal',
 'Alok Rawat',
 'Alpha Capital',
 'Alteria Capital',
 'Altimeter Capital',

In [ ]:
df[df['investors'].str.contains(' IDG Ventures')].head(50)
df[df['investors'].str.contains(' IDG Ventures')]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
259,2018-02-05,Bizongo,Consumer Internet,Aggregator For Packaging Material,Mumbai,"B Capital, International Finance Corporation (...",Private Equity,181.500
528,2017-05-10,Little Black Book,Consumer Internet,Local Recommendations and Discoveries Platform,New Delhi,"Blume Ventures, IDG Ventures & Indian Angel Ne...",Private Equity,8.250
1506,2016-04-07,Curefit,Consumer Internet,Online Preventive Healthcare Platform,Bangalore,"Accel Partners, IDG Ventures, Kalaari Capital",Private Equity,123.750
1673,2016-04-05,Lenskart,eCommerce,Eyewear & Accessories etailer,New Delhi,"International Finance Corp, TPG Growth, Adveq ...",Private Equity,495.000
1933,2016-08-02,Xpressbees,ECommerce,ECommerce Logistics solutions,Pune,"SAIF Partners, IDG Ventures India, Vertex Vent...",Private Equity,103.125
2329,2015-12-10,Tripoto,global community for travellers,NaN,New Delhi,"500 Startups, IDG Ventures & Advantedge fund, ...",Private Equity,0.000
2571,2015-01-07,Cloudcherry Analytics,CRM / Analytics platform,NaN,Chennai,"The Chennai Angels, IDG Ventures India",Seed Funding,8.250
2819,2015-08-04,FirstCry.com,eCommerce,NaN,Pune,"Silicon Valley Ventures, NEA Ventures, Valiant...",Private Equity,82.500